-- MySQL schema for guest book
CREATE DATABASE IF NOT EXISTS `guest_book` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `guest_book`;

CREATE TABLE IF NOT EXISTS `guest_entries` (
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(100) NOT NULL,
	`email` VARCHAR(190) NULL,
	`message` TEXT NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
